[tool.ruff]
# https://docs.astral.sh/ruff/
# https://docs.astral.sh/ruff/settings/
# https://docs.astral.sh/ruff/configuration/
target-version = "py310"
line-length = 110
indent-width = 4
exclude = [".git", ".venv", ".mypy_cache", "__pycache__"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false

[tool.ruff.pydocstyle]
convention = "google"

[tool.ruff.lint]
# https://docs.astral.sh/ruff/rules/
select = ["ALL"]
ignore = [
    "N803", # argument name should be lowercase : 引数名は小文字を使用します
    "N806", # variable in function should be lowercase : 関数内の変数は小文字を使用します
    "D10", # Missing docstring : docstringがありません
    "BLE001", # blind-except : 例外を捕捉する際に、例外の型を指定していません
    "INP001", # implicit-namespace-package : 暗黙的な名前空間パッケージを使用しています
    #  "T20", # print found : print文があります ※ loggingとは異なり誤って機密情報が含まれる可能性があります
    "S311", # suspicious-non-cryptographic-random-usage : 暗号学的でない乱数生成を使用しています
    #  "PTH", # Use of the `pathlib` module is preferred over `os.path` : `os.path`よりも`pathlib`モジュールの使用が推奨されています
    "ERA001", # Found commented-out code : コメントアウトされたコードがあります
    "PGH003", # Use specific rule codes when ignoring type issues : 型の問題を無視する際に具体的なルールコードを使用します
    "PGH004", # Use specific rule codes when using noqa : noqaを使用する際に具体的なルールコードを使用します
    "PLC1901", # compare-to-empty-string : 空文字の比較 if a == "": を if not a: に変更します
    "PLR1711", # useless-return : 不要なreturn文です ※ 除外すると空行の訂正をされなくなります
    "RUF001", "RUF002", "RUF003", # ambiguous unicode character : ※ 主に全角記号を使用禁止します
]
fixable = ["ALL"]
unfixable = [
    "F401", # unused-import : import文に未使用の名前があります ※削除します
]

[tool.ruff.lint.pylint]
max-args = 5            # 関数やメソッドの定義で許容される引数の最大数 (PLR0913) default: 5
max-bool-expr = 5       # 1つのif文で使用できるブール式の最大数 (PLR0916) default: 5
max-branches = 12       # 関数またはメソッド本体に許される分岐の最大数 (PLR0912) default: 12
max-locals = 15         # 関数またはメソッド本体で使用できるローカル変数の最大数 (PLR0914) default: 15
max-nested-blocks = 5   # 関数またはメソッド本体内で許可される入れ子ブロックの最大数 (PLR1702) default: 5
#  max-pos-args = 3     # 関数またはメソッドの定義で使用できる位置引数の最大数 (PLR0917) default: 3
max-public-methods = 20 # クラスに許されるパブリックメソッドの最大数 (PLR0904) default: 20
max-returns = 6         # 関数またはメソッド本体に許される return 文の最大数 (PLR0911) default: 6
max-statements = 50     # 関数またはメソッド本体に許されるステートメントの最大数 (PLR0915) default: 50

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["E402"] # Ignore `E402` (import violations) : importエラーを無視します
"**/{tests,docs,tools}/*" = ["E402"] # Ignore `E402` (import violations) : importエラーを無視します


[tool.mypy]
# https://mypy.readthedocs.io/en/stable/index.html
python_version = "3.10"
show_traceback = "True"              # mypyがクラッシュした場合にトレースバックを表示します
error_summary = "True"               # エラーメッセージの概要を表示します
pretty = "True"                      # エラーメッセージを見やすくフォーマットします
color_output = "True"                # エラーメッセージに色を付けて表示します
show_column_numbers = "True"         # エラーの発生した列番号を表示します
show_error_codes = "True"            # エラーコードを表示します
show_error_context = "True"          # エラーメッセージのコンテキストを表示します
allow_redefinition = "True"          # 同じスコープ内での変数の再定義を禁止します
allow_untyped_globals = "True"       # 型注釈がないグローバル変数の使用を禁止します
check_untyped_defs = "True"          # 型注釈がない関数やメソッドに対して型チェックを実施します
disallow_incomplete_defs = "True"    # 型注釈の一部が欠けている関数やメソッドの定義を禁止します
disallow_untyped_defs = "True"       # 型注釈がない関数やメソッドの定義を禁止します
disallow_untyped_calls = "True"      # 型注釈がない関数やメソッドの呼び出しを禁止します
disallow_untyped_decorators = "True" # 型注釈がないデコレータの使用を禁止します
ignore_missing_imports = "True"      # 型情報がないモジュールのインポートを無視します
implicit_reexport = "False"          # 型注釈がない関数やメソッドの再エクスポートを禁止します
no_implicit_optional = "True"        # Optionalの型を明示的に宣言を強制します
strict = "True"                      # すべてのstrictモード関連のオプションを有効にします
strict_equality = "True"             # 異なる型同士の等価性の比較を禁止します
strict_optional = "True"             # Noneと他の型の混在を許容しません
warn_no_return = "True"              # 戻り値がない関数やメソッドでのreturn文の省略に警告します
warn_redundant_casts = "True"        # 不要な型変換に警告します
warn_return_any = "True"             # `Any`型を返す関数やメソッドに警告します
warn_unreachable = "True"            # 到達不能なコードに警告します
warn_unused_configs = "True"         # 使用されていないconfigオプションに警告します
warn_unused_ignores = "True"         # 使用されていない`# type: ignore`コメントに警告します

[tool.poetry]
name = "mkcidr"
version = "0.1.0"
description = ""
authors = ["Aromatibus"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
netaddr = "^0.10.1"
requests = "^2.31.0"
types-requests = "^2.31.0.20240125"
tqdm = "^4.66.1"


[tool.poetry.group.dev.dependencies]
ruff = "^0.2.0"
mypy = "^1.8.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
